packages:
  - console/**

ignoredBuiltDependencies:
  - inotify

onlyBuiltDependencies:
  - '@gsknnft/bigint-buffer'
  - '@gsknnft/qwormhole'
  - '@parcel/watcher'
  - '@serialport/bindings-cpp'
  - better-sqlite3
  - core-js
  - core-js-pure
  - electron
  - esbuild
  - protobufjs
  - unrs-resolver
