packages:
  - console/**
  - sdk/**



onlyBuiltDependencies:
  - '@gsknnft/qwormhole'
  - '@serialport/bindings-cpp'
  - core-js
  - core-js-pure
  - electron
  - esbuild
  - protobufjs
  - unrs-resolver
